version: 0.2
os: linux
phases:
  install:
    runtime-versions:
        apache: 2.4
files:
    - source: /
      destination: /var/www/html
permissions:
    - object: /var/www/html
      pattern: "**"
      owner: root
      group: root
      mode: 755
      type:
        - file
hooks:
    AfterInstall:
     - location: scripts/ubunturestartapache.sh
       runas: root
